# Change these first
owner: 0rangebananaspy # Your GitHub organization or username, where this repository lives
repo: io # The name of this repository
user-agent: 0rangebananaspy
   
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  links:
    - rel: stylesheet
      href: https://raw.githubusercontent.com/0rangebananaspy/cdn/main/uploads/io.css
  # themeUrl:
  cname: io.unej.id
  robotsText: "User-agent: * \n Disallow: /"
  theme: 
  # baseUrl: /io
  name: Status Layanan Digital - Universitas Jember
  logoUrl: https://raw.githubusercontent.com/0rangebananaspy/cdn/main/uploads/tik-logo-header-192-1.webp
  introTitle: "**SLD** adalah aplikasi monitoring status layanan digital di Universitas Jember."
  introMessage: SLD memonitoring layanan digital secara **real-time**. Proses pengecekan status dilakukan setiap 5 menit sekali. Dibuat dengan Svelte dan Sapper.
  navbar:
    - title: Join Channel
      href: https://t.me/tikunej
    - title: Compare Status
      href: https://isitdownorjustme.net/
  favicon: https://raw.githubusercontent.com/0rangebananaspy/cdn/main/uploads/check.png
  faviconSvg: https://raw.githubusercontent.com/0rangebananaspy/cdn/main/uploads/check.svg

sites:
  - name: DNS 205
    check: "tcp-ping"
    url: 103.241.205.205
    port: 53
  - name: DNS 206
    check: "tcp-ping"
    url: 103.241.206.206
    port: 53
  - name: SIAKAD
    url: https://siakad.unej.ac.id
  - name: SIBAJA
    url: https://sibaja.unej.ac.id
  - name: SIJAMU
    url: https://sijamu.unej.ac.id
  - name: SIKD
    url: https://sikd.unej.ac.id
  - name: SIMANGGA
    url: https://simangga.unej.ac.id
  - name: SIMKEU
    url: https://simkeu.unej.ac.id
  - name: SIREMUN
    url: https://siremun.unej.ac.id
  - name: SEMMABA
    url: https://semmaba.unej.ac.id
  - name: MMP
    url: https://mmp.unej.ac.id
  - name: E-SKP
    url: https://eskp.unej.ac.id
  - name: E-Dokumen
    url: https://edokumen.unej.ac.id
  - name: E-Surat
    url: https://esurat.unej.ac.id/
  - name: ZOOM UNEJ-server
    url: https://unej-id.zoom.us/
  - name: UC3
    url: https://uc3.unej.ac.id
  - name: SSO
    url: https://sso.unej.ac.id
  - name: WEB UNEJ (unej.ac.id)
    url: https://unej.ac.id
  - name: Lumbung
    url: https://lumbung.unej.ac.id
  - name: Kawanda
    url: https://kawanda.unej.ac.id
  - name: Library
    url: https://library.unej.ac.id
  - name: OAILib (Open E-resources Portal)
    url: https://oailib.unej.ac.id/vufind
  - name: Journal
    url: https://journal.unej.ac.id
  - name: Jurnal
    url: https://jurnal.unej.ac.id
  - name: Repository
    url: https://repository.unej.ac.id
  - name: OER (Open Educational Resources)
    url: https://oer.unej.ac.id
  - name: Taman Kebangsaan
    url: https://tamankebangsaan.unej.ac.id
  - name: API-Mobile
    check: "tcp-ping"
    url: 103.241.205.85
  - name: API-Akademik
    check: "tcp-ping"
    url: 103.241.205.114
  - name: API-Auth
    check: "tcp-ping"
    url: 103.241.205.115
  - name: API-MMP
    check: "tcp-ping"
    url: 103.241.205.116
  - name: API-Helpdesk
    check: "tcp-ping"
    url: 103.241.205.117
  - name: API-Clinic
    check: "tcp-ping"
    url: 103.241.205.118
  - name: API-Study
    check: "tcp-ping"
    url: 103.241.205.120
  - name: API-KRS
    check: "tcp-ping"
    url: 103.241.205.121
  - name: API-Slims
    check: "tcp-ping"
    url: 103.241.205.122
  - name: API-Services
    check: "tcp-ping"
    url: 103.241.205.24
  - name: Posko UTBK
    url: https://posko.unej.ac.id
  - name: Dashboard
    url: https://dashboard.unej.ac.id
  - name: Data MBKM
    url: https://datambkm.unej.ac.id
  - name: Klise
    url: https://klise.unej.ac.id
  - name: Assesor BKD
    url: https://bkd.unej.ac.id
  - name: Ambara
    url: https://ambara.unej.ac.id
  - name: PPID
    url: https://ppid.unej.ac.id
  - name: LMS PPG
    url: https://lmsppg.unej.ac.id
  - name: Latte
    url: https://latte.unej.ac.id
  - name: Lavoro
    url: https://lavoro.unej.ac.id
  - name: VA Bill
    url: https://vabill.unej.ac.id
  - name: OPTIMA BMN
    url: https://optima-bmn.unej.ac.id
  - name: SIM RSGM
    url: https://simrsgm.unej.ac.id
  - name: QR Event
    url: https://qr.unej.ac.id
  - name: Eproc
    url: https://eproc.unej.ac.id
  - name: ICOGEF PSG
    url: https://icogef.psg.unej.ac.id
  - name: SIMULAN
    url: https://simulan.unej.ac.id
  - name: Neo Feeder 2023
    url: https://feeder.unej.ac.id
  - name: GatewayNET
    url: http://gw.unej.id
  - name: SRD
    url: https://srd.unej.ac.id
  - name: CE & CP Server
    url: https://ce.svr.unej.ac.id
  - name: PocketBase
    url: https://pb.unej.id/_/#/login

i18n:
  footer: Aplikasi ini dibuat secara [open source](https://io.unej.id), oleh [UPA TIK](https://tik.unej.ac.id). Dikelola oleh Techies, Sugus, Kiplink, & MiminTI.
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
